# Generated by Django 4.2.7 on 2024-01-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_code',
            field=models.CharField(default='573319', max_length=6, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=40, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
    ]
