# Generated by Django 4.2.7 on 2024-02-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.CharField(default='067189', max_length=6, verbose_name='Код'),
        ),
    ]
